cp ./dist/all.*.css ./favicon.ico ../apps/public/;
cp ./dist/all.*.css ./favicon.ico ../index-differ/public/;
cp ./dist/all.*.css ./favicon.ico ../index-manager/public/;
cp ./dist/all.*.css ./favicon.ico ../logs/public/;
cp ./dist/all.*.css ./favicon.ico ../metaparams/public/;
cp ./dist/all.*.css ./favicon.ico ../relevance-testing/public/;
cp ./dist/all.*.css ./favicon.ico ../index-analyzer/public/;
cp ./dist/all.*.css ./favicon.ico ../insights-ui/public/;
cp ./dist/all.*.css ./favicon.ico ../transform/public/;
