http:
  - target: web

build:
  - name: web
    buildArgs:
      - name: VUE_APP_METAPARAMS_BACKEND_ENDPOINT
        value: __VUE_APP_METAPARAMS_BACKEND_ENDPOINT__

compute:
  - name: web
    port: 8080
    environment:
      - name: LANG
        value: en_US.UTF-8
      - name: NODE_ENV
        value: production
      - name: TOOLS_ENDPOINT
        secretName: tools-endpoint
      - name: TOOLS_INTERNAL_ENDPOINT
        secretName: tools-internal-endpoint
      - name: VUE_APP_APP_ID
        secretName: vue-app-app-id
      - name: VUE_APP_PROXY_ENABLED
        value: 'true'
      - name: VUE_APP_SEARCH_ONLY_API_KEY
        secretName: vue-app-search-only-api-key
      - name: VUE_APP_TOOLS_INTERNAL_ENDPOINT
        secretName: vue-app-tools-internal-endpoint
