http:
  - target: web

build:
  - name: web

compute:
  - name: web
    port: 8080
    environment:
      - name: VUE_APP_METAPARAMS_BACKEND_ENDPOINT
        secretName: vue-app-metaparams-backend-endpoint
